# Generated by Django 2.0 on 2018-08-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestID', models.CharField(max_length=10)),
                ('userID', models.CharField(max_length=10)),
            ],
        ),
    ]
