# Generated by Django 2.0 on 2018-09-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='querydate',
            field=models.CharField(default='', max_length=10),
        ),
    ]
