# Generated by Django 2.0 on 2018-09-06 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_data', '0002_requests_querydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='querydate',
            new_name='requestdate',
        ),
    ]
