# Generated by Django 2.0 on 2018-08-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyID', models.CharField(max_length=20)),
                ('taxNumber', models.CharField(max_length=20)),
                ('bossID', models.CharField(max_length=10)),
                ('adminID', models.CharField(max_length=10)),
                ('departNames', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('name2', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=20)),
                ('departName', models.CharField(max_length=10)),
                ('modelLocation', models.CharField(max_length=10)),
            ],
        ),
    ]
