# Generated by Django 2.0 on 2018-08-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0003_personal_info_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='company',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
