# Generated by Django 2.0 on 2018-08-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0004_auto_20180830_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='company',
            field=models.CharField(max_length=20),
        ),
    ]
