# Generated by Django 2.0 on 2018-08-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0005_auto_20180830_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
