# Generated by Django 2.0 on 2018-08-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0006_auto_20180830_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
