# Generated by Django 2.0 on 2018-09-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0007_company_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='adminID',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='bossID',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='companyID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='departNames',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='taxNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='company',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='departName',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='modelLocation',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='userID',
            field=models.CharField(default='', max_length=10),
        ),
    ]
