# Generated by Django 2.0 on 2018-09-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0008_auto_20180904_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='title',
            field=models.IntegerField(default=0),
        ),
    ]
