# Generated by Django 2.0 on 2018-09-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0009_personal_info_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='departNames',
            field=models.CharField(default='', max_length=500),
        ),
    ]
