# Generated by Django 2.1 on 2018-09-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0013_auto_20180907_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
