# Generated by Django 2.1 on 2018-09-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0014_auto_20180907_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='email',
        ),
    ]
