# Generated by Django 2.1 on 2018-09-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0017_personal_info_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='title2',
        ),
    ]
