# Generated by Django 2.1 on 2018-09-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_data', '0003_auto_20180906_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day10',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day11',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day12',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day13',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day14',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day15',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day16',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day17',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day18',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day19',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day2',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day20',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day21',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day22',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day23',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day24',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day25',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day26',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day27',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day28',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day29',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day3',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day30',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day31',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day4',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day5',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day6',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day7',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day8',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='day9',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_apr',
            name='userID',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day10',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day11',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day12',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day13',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day14',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day15',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day16',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day17',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day18',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day19',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day2',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day20',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day21',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day22',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day23',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day24',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day25',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day26',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day27',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day28',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day29',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day3',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day30',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day31',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day4',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day5',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day6',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day7',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day8',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='day9',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_aug',
            name='userID',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day10',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day11',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day12',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day13',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day14',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day15',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day16',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day17',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day18',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day19',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day2',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day20',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day21',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day22',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day23',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day24',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day25',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day26',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day27',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day28',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day29',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day3',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day30',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day31',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day4',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day5',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day6',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day7',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day8',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='day9',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_dec',
            name='userID',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day10',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day11',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day12',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day13',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day14',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day15',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day16',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day17',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day18',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day19',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day2',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day20',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day21',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day22',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day23',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day24',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day25',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day26',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day27',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day28',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day29',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day3',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day30',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day31',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day4',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day5',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day6',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day7',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day8',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='day9',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_feb',
            name='userID',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day10',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day11',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day12',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day13',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day14',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day15',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day16',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day17',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day18',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day19',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day2',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day20',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day21',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day22',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day23',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day24',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day25',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day26',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day27',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day28',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day29',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day3',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day30',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day31',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day4',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day5',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day6',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day7',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day8',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='day9',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jan',
            name='userID',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day10',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day11',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day12',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day13',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day14',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day15',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day16',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day17',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day18',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day19',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day2',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day20',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day21',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day22',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day23',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day24',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day25',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day26',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day27',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day28',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day29',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day3',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day30',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day31',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day4',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day5',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day6',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day7',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day8',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='day9',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_july',
            name='userID',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day10',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day11',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day12',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day13',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day14',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day15',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day16',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day17',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day18',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day19',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day2',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day20',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day21',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day22',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day23',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day24',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day25',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day26',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day27',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day28',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day29',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day3',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day30',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day31',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day4',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day5',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day6',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day7',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day8',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='day9',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_jun',
            name='userID',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day10',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day11',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day12',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day13',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day14',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day15',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day16',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day17',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day18',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day19',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day2',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day20',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day21',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day22',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day23',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day24',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day25',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day26',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day27',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day28',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day29',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day3',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day30',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day31',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day4',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day5',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day6',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day7',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day8',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='day9',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_mar',
            name='userID',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day10',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day11',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day12',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day13',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day14',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day15',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day16',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day17',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day18',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day19',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day2',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day20',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day21',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day22',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day23',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day24',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day25',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day26',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day27',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day28',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day29',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day3',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day30',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day31',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day4',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day5',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day6',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day7',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day8',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='day9',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_may',
            name='userID',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day10',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day11',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day12',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day13',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day14',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day15',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day16',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day17',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day18',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day19',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day2',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day20',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day21',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day22',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day23',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day24',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day25',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day26',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day27',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day28',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day29',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day3',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day30',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day31',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day4',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day5',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day6',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day7',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day8',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='day9',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_nov',
            name='userID',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day10',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day11',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day12',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day13',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day14',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day15',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day16',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day17',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day18',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day19',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day2',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day20',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day21',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day22',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day23',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day24',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day25',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day26',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day27',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day28',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day29',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day3',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day30',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day31',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day4',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day5',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day6',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day7',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day8',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='day9',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_oct',
            name='userID',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day10',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day11',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day12',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day13',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day14',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day15',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day16',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day17',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day18',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day19',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day2',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day20',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day21',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day22',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day23',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day24',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day25',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day26',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day27',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day28',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day29',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day3',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day30',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day31',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day4',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day5',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day6',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day7',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day8',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='day9',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance_data_sep',
            name='userID',
            field=models.CharField(default='', max_length=25),
        ),
    ]
